//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sample.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Subject
    {
        public Subject()
        {
            this.Student_Details = new HashSet<Student_Details>();
        }
    
        public int Subject_ID { get; set; }
        public string Subject1 { get; set; }
    
        public virtual ICollection<Student_Details> Student_Details { get; set; }
    }
}
