//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Helper.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class School
    {
        public int Id { get; set; }
        public string Department { get; set; }
        public int NumberofStudents { get; set; }
        public string Teachers { get; set; }
        public string Director { get; set; }
    }
}
